Terminal/Discord_Fork

_bots/341980888239702017.md

add jennifer

---

_bots/463733562601111553.md

Please can you add the GlobalBanz Discord Bot to your Bot List, thank you <3

Added GlobalBanz

---

_bots/310578566695878658.md

Added Endless

---

_bots/305277118105911296.md

Updated short and long descriptions for my bot.

[Update] Homer (305277118105911296)

---

_bots/305277118105911296.md

I hope I'm not annoying with all these PRs c:
Should be the last one, updating translation information

[Update] Homer (305277118105911296) #2

---

_bots/439435998078959616.md

I hate to post another pull request right after the first one but I would like to update this and this seems to be the only way.

Update Power Glove

---

_bots/388823187246546948.md

Let me know if I messed up something, especially the long description part.

Adding Dragon Loli

---

_bots/388633353743630336.md

I finished a fucking project @lepon01 and I'm adding it here. Be proud of me

GrapeBot verification

---

_bots/169678500893163520.md
_bots/388633353743630336.md

Added bot PikaGirl

---

_bots/257547382277931009.md

Accept me please
i will bribe @Devoxin for this
---

Adding Matt Parker

---

_bots/261912303132344320.md

Adding Oliver

---

_bots/365958655926992896.md

Adding Luki

---

_bots/367202192609902593.md

Adding Gearz

---

_bots/371320386693890048.md

Adding Brotat

---

_bots/284196779044503553.md

Adding mBot

---

_bots/300800171988484096.md

Adding Bender

---

_bots/443053627419000833.md

Adding Granz

---

_bots/372022813839851520.md

Adding AltDentifier

---

_bots/303181184718995457.md

Prefix is customizable and also works if you tag the bot instead of the prefix :)
---

Adding PenguBot

---

_data/fr/strings.yml

Pull request en français parce que baguette

---

_bots/fr/305277118105911296.md

French version for Homer (305277118105911296)

---

_bots/322203879208910849.md

Adding Spotify Bot

---

_servers/188752295108935680.md

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512
^
to prevent lame edits this message is signed
also 7coil is awesome
-----BEGIN PGP SIGNATURE-----
Version: Keybase OpenPGP v2.0.77
Comment: https://keybase.io/crypto
wsBcBAABCgAGBQJbgeIzAAoJEIRbwGc5Ha4IKOgH/33saDSNvj4TzT81D7xiWj81
WalspHGx7WLKY1ZebfNgSawfn/4rvpmoK22IZxfeiLgVuGUsActAWl8ewjWMqgMZ
wgaB47O0frGE5uWLBBauW8oaRiIx6WrSVAuMyv+qvu7VsvMnWej+TFs0rBO1IZM9
nC3ZTKqroB0sa14txnqiymivFmFDqG6vDQTuVuIZMyNfXkX5/A1V0DAZ2sWC+uNL
V//rt19y8PdlH2GKcEn1Qm+yr3PB1moCq9sFzRHNV0iNpglJNn29ZzTdkaTTfNWP
s22Gmp11baBcpCMPZV+bJfsgOkc5y05DfyQZ0CttK2OwSiywgcMmF8/ppGnWHu0=
=BDgF
-----END PGP SIGNATURE-----

not sure if i am allowed to add a server

---

_data/fr/locale.yml

Speaking the baguette makes me a good translator, I guess

Translate more

---

_bots/288831103895076867.md

Adding Reknown

---

_bots/454713729649475594.md

Adding LxiBot

---

_data/en/strings.yml
_includes/intro.html
netlify.toml

maybe too easy?!?!?!?
test using [https://app.netlify.com/start/deploy?repository=https://github.com/comp500/Discord_Fork](https://app.netlify.com/start/deploy?repository=https://github.com/comp500/Discord_Fork) (delete your forked list when done, it's just a testing repo)

make forking discord fork easier

---

_bots/389083091655852032.md

Adding WednesdaysBot

---

_bots/402116404301660181.md

Adding Groovy

---

_bots/478232314577551371.md

Adding Furrboye

---

_bots/220644154177355777.md

Adding Watora

---

_bots/220644154177355777.md

Editing my bot

---

_bots/213466096718708737.md
_config.yml
_includes/footer.html
_includes/head.html
_includes/intro.html
_layouts/item.html
_pages/api/bots/all.json
_pages/api/servers/all.json
_plugins/ExportItems.rb
test.txt
webpack/helpers/elements.js
webpack/pages/item.js
webpack/pages/list.js

```diff
+ JSON files show all frontmatter as is
+ Individual bot, server and documentation JSON outputs
+ "keys.json" show all files accessable
+ Added "primary_key" to JSON, which points to the unique identifier for that file. Should also be the file name
+ IDs are corrected to strings.
+ Search is fixed. (with a bodge)
- API has changed.
```

JSON Endpoint Update

---

_bots/470989648747954176.md

Adding EquippedDroid

---

466007757183516703.md

XtraCord bot is coded in discord.py library, its still under development moderators can test it out if needed to assure its a safe bot!

XtraCord Bot

---

_bots/472726264805982209.md

Adding Rixa 3

---

CNAME

Delete the CNAME file

---

_bots/472726264805982209.md

Reverts Terminal/Discord_Fork#84
Level up fixed

Revert "Revert "Adding Rixa 3""

---

_bots/488092297452322826.md

Adding MonsterHub

---

collections/_bots/425382319449309197.md

Finally took my time to fix the typos in the codeblock...

Fixed Markdown-issues

---

collections/_bots/270904126974590976.md

Adding Dank Memer

---

collections/_bots/408741303837392926.md

There are 3 NSFW commands at the moment. And you may run into a few broken commands as I have not yet been able to get around to fixing everything at the moment.
---

Adding CripsBot

---

collections/_bots/460545687592108032.md

git commit -m "added stuff"
---

Adding Roleplayer

---

collections/_bots/454334584327372802.md

The bot needs to have a channel set as ticket-channel, to actually create tickets.
---

Adding Supporto

---

collections/_bots/406082711271374848.md

Adding Aru!

---

collections/_bots/456633518882160642.md

Adding YouTube

---

collections/_bots/323128638444929025.md

Fix & update imported data of Shuvi

---

data/en/bots/285480424904327179.md

I am adding an optional extended description to this proposed file change uwu

Update repo owner

---

collections/_bots/454334584327372802.md

Added missing commands and information.

Update Bot-information of Supporto

---

collections/_servers/398998849026261003.md

add advaithbot server

---

collections/_bots/193403332046487552.md

Adding HawkBot

---

collections/_bots/388633353743630336.md

Update avatar of Grape

---

collections/_bots/437439973751521280.md

Adding JackSucksAtBot

---

collections/_bots/480639227516944384.md

Adding Hibiki

---

data/en/bots/330003632298917889.md
gatsby-config.js
gatsby-node.js
node/downloadImages.js
package-lock.json
package.json
src/components/Carousel/index.js
src/components/Carousel/index.scss
src/components/CarouselItem/index.js
src/components/CarouselItem/index.scss
src/components/Footer/index.js
src/components/Intro/index.js
src/components/Intro/index.scss
src/locales/en.json
src/pages/bots.js
src/pages/edit.js
src/pages/index.js

This pull request adds a new "scrolly thing" for the homepage.
_some new translations may be required_
Development site: https://v2-homepage--discordbots.netlify.com/

V2 homepage

---

data/en/servers/496676221749428246.md

Adding Daikin Communities

---

data/en/bots/285480424904327179.md

Sexy cover for a sexy bot

---

data/en/bots/495437730810036225.md

Thighs are sexy so here is a sexy cover that's more legs then thighs but equally as sexy

Sexy cover for yet another sexy Bots

---

data/en/bots/454334584327372802.md

Literally just removed black pixels at the left, even tho they didn't do that much bad...
:pleasedonthurtme:

Update the cover-image

---

data/en/bots/495437730810036225.md

better avatar

---

data/en/servers/440526421388165120.md

Adding Boobbot

---

data/en/bots/346346285953056770.md

Adding Minecraft

---

data/en/bots/377857449236889600.md

Adding Tune

---

data/en/bots/358785023286968323.md

Adding Pikacord

---

data/en/bots/504194448540958726.md

Adding Akatsuki

---

data/en/bots/310039170792030211.md

Adding NekoBot

---

data/en/bots/504819339422072834.md

Adding GitTags

---

src/locales/fr.json

- Updated French translation with lastest strings
- More "human" text too

Translation: Complete and better French version

---

data/en/bots/450351487642501126.md

Adding Sana

---

src/components/Global/index.js

I tried to not beak everything, let's see if the deploy works lmao

Better meta tags

---

data/en/bots/462212977882562571.md

Adding Mardatonne

---

data/en/bots/495743974028476446.md

Adding Psychic

---

data/en/bots/268420199370194944.md

Adding BlueBot
